---
- name: Install ca-certificates and curl
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: true

- name: Ensure keyrings directory exists with correct permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker official repository to Apt sources (DEB822 Format)
  ansible.builtin.shell: |
    cat <<EOF > /etc/apt/sources.list.d/docker.sources
    Types: deb
    URIs: https://download.docker.com/linux/ubuntu
    Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
    Components: stable
    Architectures: $(dpkg --print-architecture)
    Signed-By: /etc/apt/keyrings/docker.asc
    EOF
  changed_when: true

- name: Force apt update after adding official repository
  ansible.builtin.apt:
    update_cache: true

- name: Install official Docker and Compose plugin
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3-docker
    state: present

- name: Ensure docker service is running and enabled
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Create a directory for Elasticsearch data on the host
  ansible.builtin.file:
    path: /var/lib/elasticsearch/data
    state: directory
    owner: 1000
    group: 1000
    mode: '0775'

- name: Start an Elasticsearch container without security
  community.docker.docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:9.5.3
    state: started
    restart_policy: always
    ports:
      - "9200:9200"
      - "9300:9300"
    env:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"
    volumes:
      - /var/lib/elasticsearch/data:/usr/share/elasticsearch/data